# Notification Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: library/notification:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8085
---
# Notification Service
apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP